### ISSUE TITLE
Determine size/count of full collection of EADs

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#356]
In ASpace Prod we have:

Total published/non-suppressed EADs: 2398 (170MB)

**Archive of Recorded Sound**
Resources/Collections: 238
Published Resources/Collections: 37
Count in OAC: 141

**Cubberley Education Library**
Resources/Collections: 1829
Published Resources/Collections: 1816
Count in OAC: 0

**Department of Special Collections and University Archives**
Resources/Collections: 10055
Published Resources/Collections: 515
Count in OAC:
- Manuscripts: 1200
- Rare Books Division: 7
- UA: 2473

**East Asia Library**
Resources/Collections: 28
Published Resources/Collections: 1
Count in OAC: 2

**Engineering Library**
Resources/Collections: 3
Published Resources/Collections: 0
Count in OAC: 0

**Graduate School of Business Archives**
Resources/Collections: 0
Published Resources/Collections: 0
Count in OAC: 0

**Medical History Center**
Resources/Collections: 3
Published Resources/Collections: 3
Count in OAC: 3

**Music Library**
Resources/Collections: 5
Published Resources/Collections: 0
Count in OAC: 5

**Sezione dei manoscritti e dei rari**
Resources/Collections: 2
Published Resources/Collections: 0
Count in OAC: 0

**Stanford University. Libraries.**
Resources/Collections: 1
Published Resources/Collections: 0
Count in OAC: 0

**Stanford Law School**
Resources/Collections: 36
Published Resources/Collections: 2
Count in OAC: 0

**Virtual Tribunals**
Resources/Collections: 1
Published Resources/Collections: 1
Count in OAC: 0

**Comment by dinahhandel** [comment]
This question has been posed to archivists and the responses are: 

"1. Discrepancies in SPEC…since we haven’t historically needed to check “published” in order to export, there are many guides where this would need to be reconciled. 
However, some guides might have been published before, but are being edited - new addenda added. We would not want them published again until that is completed.
It is very likely that old guides imported into archivists toolkit (originally) were never marked as published." - Glynn Edwards

"There are several reasons for the published unpublished discrepancy. 

Aligning with Glynn's comment. It was not required by OAC, for many years, checking the "publish" box was not done. This has been rectified in the last 2 years, and any FA's that are updated get this adjusted. This has not been done comprehensively as a remediation process. 

As far as a gap between the number of OAC FA's and ASpace resource records (and numbered collections. There are many collection resource records that are placeholders for collections that are not processed, exist to track items that were sent to SAL3 before processing [when that was a thing], or are partially processed collections that were not completed for various reasons. Sometimes resource records have been created for internal use and not necessarily for publication. 

I would expect to address the ARclight publication issue there would need to be remediation to address FA's that need to have "publish" checked." - Nathan Coy
