### ISSUE TITLE
How do we want to manage/handle findings aids that are deleted/unpublished from ArchiveSpace?

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/stanford-arclight#365]

**Comment by dinahhandel** [comment]
If a finding aid is marked as unpublished in ArchivesSpace, upon the next scheduled update to ArcLight, the data should be removed from the ArcLight environment. We should also consider a manual way to remove data immediately upon request.

**Comment by corylown** [comment]
A couple of complications related to this:

- It sounds like published finding aids are being set to unpublished while they're being edited. But the intent is to prevent updating the public finding aid until it is ready rather than deleting it. See Glynn's email from Nov. 15:
> However, some guides might have been published before, but are being edited - new addenda added. We would not want them published again until that is completed. 

- If we're going to support a manual workflow in addition to an automated one we'll need to be able to tell the difference in ArcLight between manually added and automatically added records otherwise they would be deleted if they are unpublished.

**Comment by marlo-longley** [comment]
We need to know from archivists -- can we handle "unpublishing" collections manually for now? 

It adds complexity to the code and we aren't sure how it works -- unpublished, suppressed, is there a standard practice? Does this ever happen at all?

**Comment by marlo-longley** [comment]
Archivists are comfortable with a manual delete process because it’s rare and how it’s handled currently with OAC.
