### ISSUE TITLE
Add visual indication that components are loading

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#441]
Provide some kind of visual update when Expand is clicked and components are taking time to load.

(Should this be added in upstream Arclight?)

**Comment by taylor-steve** [comment]
There's already a simple throbber, I think? This grey box that goes from light grey to dark grey:

![Image](https://github.com/sul-dlss/stanford-arclight/assets/4421877/9babc690-39ca-48d2-8775-fd4add7d9502)

https://github.com/projectblacklight/arclight/blob/713f16110fb31041d80abea288cc5273bf21cfb7/app/assets/stylesheets/arclight/modules/hierarchy_and_online_contents.scss#L49

Do we have an idea of what style we'd prefer?

**Comment by corylown** [comment]
@taylor-steve can you verify if the grey box shows up when you click the "Expand" button after it loads the first part of the list?

**Comment by taylor-steve** [comment]
Anybody have an opinion if the placeholder loading animation should be above, below, or in lieu of the Expand button? 
![Screenshot 2024-05-07 at 3 57 18 PM](https://github.com/sul-dlss/stanford-arclight/assets/4421877/e3aa7e12-68a9-4a5d-82d2-f8ee90fc9253)
![Screenshot 2024-05-07 at 3 55 57 PM](https://github.com/sul-dlss/stanford-arclight/assets/4421877/818498e5-6cdd-461d-8a0c-26fc31f6eaa8)
![Screenshot 2024-05-07 at 3 55 12 PM](https://github.com/sul-dlss/stanford-arclight/assets/4421877/56ecf92c-5910-4d9a-8397-d90f6986cd4e)

Above/below are small, hopefully uncontroversial, upstream CSS changes. Removing the button could be slightly more controversial, but easy.

If we aren't concerned with position, I'll default to below because it's one new line 😄

**Comment by corylown** [comment]
I don't have a strong opinion. @astridu @dinah do either of you have a preference for how the loading animation displays in relation to the list and the expand button?

**Comment by taylor-steve** [comment]
@astridu @dinahhandel also are we planning on having a custom/different loading animation beyond the placeholder? If we are, that would impact what goes upstream versus local. Thanks.

**Comment by dinahhandel** [comment]
@corylown @taylor-steve I'll ask @astridu today at our design meeting.

**Comment by dinahhandel** [comment]
@taylor-steve @corylown we think it should show above the expand. Thanks! cc @astridu
