### ISSUE TITLE
Creators and other named agents are not published in ASpace

### ISSUE THREAD

**Issue by corylown** [sul-dlss/stanford-arclight#486]
Is there any reason why we can't just published all of these? It's the reason (as far as I can tell) that we're not populating the creator field when pulling records from ASpace.

**Comment by dinahhandel** [comment]
I'll write the archivists today and ask this question.

**Comment by dinahhandel** [comment]
Here's the first response I received: 

"Hi Dinah,
I'll try to tackle the later question first since it's fresher in my mind. Will try to respond re others soon.
By creator field I'm guessing you're referring to the names under Agent Links, where both creator and source are usually listed (when they are the same, the name will publish twice in OAC, without their relator codes). This is the first I've heard of publishing quirks for this field, but in general I will vouch for inconsistencies with Publishing in AS. I have recently set several guides to "publish all" only to find less than everything in the exported xml. 
What I'd like to reiterate is that the only choice we made in regard to the publish checkboxes is for a workaround to avoid printing old Archivist Toolkit IDs in our finding aids, which began a few years ago and continues to be a problem. As for making guides available, AS has always been a backend from which we choose specific files to export. Unfortunately, this means there's a great big pile of wrong there, or at least unpopulated or permanently in process records.
Hope you are doing well!
Franz"

**Comment by corylown** [comment]
Relevant links to API docs:

https://archivesspace.github.io/archivesspace/api/#publish-a-corporate-entity-agent-and-all-its-sub-records
https://archivesspace.github.io/archivesspace/api/#publish-a-family-agent-and-all-its-sub-records
https://archivesspace.github.io/archivesspace/api/#publish-an-agent-person-and-all-its-sub-records
https://archivesspace.github.io/archivesspace/api/#publish-a-software-agent-and-all-its-sub-records

**Comment by corylown** [comment]
We've tried this on stage with success. We need to verify that no private information like contact information is published. Archivists are interested in having us publish Agents on production if we can ensure that private info remains private.

**Comment by corylown** [comment]
This ASpace documentation about agents (https://archivesspace.org/wp-content/uploads/2017/01/Agent-Specification-20120323.pdf) indicates that contact information is never visible except to authorized staff users of ASpace:

> Once completed and saved, a name contact information record will be listed in the display for name contact information, with the proviso that the name contact sub-record is only displayed to the staff of the repository that created it and only those staff within the repository that are authorized to view it.

**Comment by dinahhandel** [comment]
I'm happy to write back to the archivists about that separately, but it would seem like we can proceed with identifying a time to do that in ArchivesSpace -prod. I'm also thinking we should let Michael Olson know.

**Comment by taylor-steve** [comment]
I wrote a tool to do this (hopefully nobody else had anything in-flight):

https://gist.github.com/taylor-steve/e8d4c57b2e6b35944625604733bfa5a3
