### ISSUE TITLE
Stanford-branded theme

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/stanford-arclight#91]

**Comment by ggeisler** [comment]
@anarchivist Are there any special considerations we need to make, branding-wise, given we're including (_I think?_) Hoover into the stanford-arclight instance? In other words, our usual branding includes the standard Stanford footer, but also includes a SUL footer and a "Stanford Libraries" logo in the top brand bar. Is that okay that Hoover is included within an application that is branded as Stanford Libraries?

**Comment by anarchivist** [comment]
@ggeisler (apologies for the delay; catching up from DLF).

At a first pass, I think it's less critical to address specific considerations for our local instance of ArcLight - especially for this phase, which focuses on just updating the test instance.\* My assumption here is that ArcLight is like (or perhaps may become integrated into) SearchWorks, which is branded with the Stanford Libraries logo and SUL footer:

<img width="1303" alt="Screen Shot 2019-10-17 at 8 11 55 PM" src="https://user-images.githubusercontent.com/73732/67056531-71ab3480-f11a-11e9-96a5-4968703df8b6.png">

Of course, SearchWorks also contains holdings of non-SUL libraries, like some of the coordinates (Hoover, GSB, Lane, Crown) and Tanner:

<img width="340" alt="Screen Shot 2019-10-17 at 8 15 50 PM" src="https://user-images.githubusercontent.com/73732/67056710-30675480-f11b-11e9-94b3-1960fa43e7af.png">

* Changes in branding may come up as we get more feedback on our local instance, but that's not work we intend to complete immediately.

**Comment by ggeisler** [comment]
Okay @anarchivist, the analogy to Searchworks makes perfect sense, thanks!

**Comment by jvine** [comment]
This is a basic set of specs to make Arclight correspond fairly closely with SearchWorks. Details will require tweaking, and @ggeisler will likely have more input. Goal is to get a SearchWorks-y starting point.

## Header and search bar

- [ ] Start with base styles from My Library Account for body, headings, `<a>` and colour variables.
- [ ] Add Feedback link (and form!) to topbar
- [ ] Replace Arclight logo w SUL logo; link to library.stanford.edu
- [ ] Move Bookmarks from topbar to al-masthead
- [ ] Suppress the History link
- [ ] Add icons to al-masthead links
- [ ] Style header area as in My Library Account

<img width="1144" alt="header and search bar" src="https://user-images.githubusercontent.com/6945691/67443401-90e21000-f5b9-11e9-95bb-3dca62be7380.png">

## Search results

- [ ] Facets match SearchWorks style
- [ ] Individual results are in boxes with same spacing as SW.
- [ ] The search results and controls are substantially different from SW, but the SW styling turned out to be messy to achieve and maintain. For now, use "default" button styling with $stone for the "active" state.
- [ ] Remove the `.navbar` styling from around the `h2.facets-heading` to correct its alignment

<img width="1132" alt="search results" src="https://user-images.githubusercontent.com/6945691/67443534-254c7280-f5ba-11e9-91ac-c4a6289b7480.png">

## Component page w tabs

- [ ] Overall tab borders are $cloud
- [ ] Inactive tabs have $stone background
- [ ] Selected nav has $sage background

<img width="1149" alt="component tabs" src="https://user-images.githubusercontent.com/6945691/67444156-bb819800-f5bc-11e9-8869-4c23bd8fb2ff.png">

### Tool box on component page

- [ ] Use $blue for the Request button as in My Library & SW.

<img width="250" alt="toolbox detail" src="https://user-images.githubusercontent.com/6945691/67444125-9f7df680-f5bc-11e9-910a-21e7baac37c2.png">

## General notes

- [ ] all borders should be $cloud
- [ ] any references to pixel-specific font sizes should be removed
